config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"

  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'follower', to: 'relationships#follower'
    get 'followed', to: 'relationships#followed'
  end

  get 'search', to: 'searches#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User', foreign_key: :follower_id
  belongs_to :followed, class_name: 'User', foreign_key: :followed_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :followers, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followeds, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy


  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, presence:true

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def follow_to?(user)
    followers.exists?(followed_id: user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:root, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_in_path_for(resource)
    books_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    # comment = current_user.book_comments.new(book_comment_params)
    # comment.book_id = book.id
    comment = BookComment.new(
      user_id: current_user.id,
      book_id: @book.id,
      comment: book_comment_params[:comment])
    comment.save

    # redirect_to book_path(book.id)
  end

  def destroy
    @book = Book.find(params[:book_id])
    BookComment.find(params[:id]).destroy

    # redirect_to book_path(params[:book_id])
  end

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @new_book = Book.new
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    # favorite = current_user.favorites.new(book_id: book.id)
    favorite = Favorite.new(user_id: current_user.id, book_id: @book.id)
    favorite.save

    # redirect_to request.referer
  end

  def destroy
    @book = Book.find(params[:book_id])
    # favorite = current_user.favorites.find_by(book_id: book.id)
    favorite = Favorite.find_by(user_id: current_user.id, book_id: @book.id)
    favorite.destroy

    # redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def follower
    # フォローしているユーザー一覧
    @relationships = Relationship.where(follower_id: params[:user_id])
  end

  def followed
    # フォローされているユーザー一覧
    @relationships = Relationship.where(followed_id: params[:user_id])
  end

  def create
    user = User.find(params[:user_id])
    # favorite = current_user.favorites.new(book_id: book.id)
    relationship = Relationship.new(follower_id: current_user.id, followed_id: user.id)
    relationship.save

    redirect_to request.referer
  end

  def destroy
    user = User.find(params[:user_id])
    # favorite = current_user.favorites.find_by(book_id: book.id)
    relationship = Relationship.find_by(follower_id: current_user.id, followed_id: user.id)
    relationship.destroy

    redirect_to request.referer
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @model = params[:model]
    @content = params[:content]
    @type = params[:type]

    if @model == :book.to_s
      if @type == :perfect.to_s
        @books = Book.where("title = ?", params[:content]).or(Book.where("body = ?", params[:content]))
      elsif @type == :partial.to_s
        @books = Book.where("title LIKE ?", "%#{params[:content]}%").or(Book.where("body LIKE ?", "%#{params[:content]}%"))
      end
    elsif @model == :user.to_s
      if @type == :perfect.to_s
        @users = User.where("name = ?", params[:content]).or(User.where("introduction = ?", params[:content])).or(User.where("email = ?", params[:content]))
      elsif @type == :partial.to_s
        @users = User.where("name LIKE ?", "%#{params[:content]}%").or(User.where("introduction LIKE ?", "%#{params[:content]}%")).or(User.where("email LIKE ?", "%#{params[:content]}%"))
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_book-comment.html.erb
<% book.book_comments.each do |book_comment| %>
<tr class="book-comment-item">
  <td><%= link_to book_comment.user do %>
    <%= image_tag book_comment.user.get_profile_image, size:"100x100" %><br>
    <%= book_comment.user.name %>
    <% end %>
  </td>
  <td colspan="5">
    <%= book_comment.comment %>
  </td>
  <td>
    <% if book_comment.user == current_user %>
    <%= link_to "削除", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true %>
    <% end %>
  </td>
</tr>
<% end %>

app/views/book_comments/create.js.erb
$("#book-comment-form").closest("table").find(".book-comment-item").remove();
$("#book-comment-form").before("<%= j(render 'book-comment', book: @book) %>");

app/views/book_comments/destroy.js.erb
$("#book-comment-form").closest("table").find(".book-comment-item").remove();
$("#book-comment-form").before("<%= j(render 'book-comment', book: @book) %>");

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <%= render 'layouts/errors', obj: @book %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user.id) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td id="favorite-btn-<%= book.id %>">
          <%= render "favorites/favorite-btn", book: book %>
        </td>
        <td>コメント数:<%= book.book_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @new_book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to @book.user do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td id="favorite-btn-<%= @book.id %>">
            <%= render "favorites/favorite-btn", book: @book %>
          </td>
          <td>コメント数:<%= @book.book_comments.count %></td>
          <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" if @book.user == current_user %></td>
          <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}" if @book.user == current_user %></td>
        </tr>
        <%= render "book_comments/book-comment", book: @book %>
        <tr id="book-comment-form">
          <td colspan="7">
          <%= form_with model: [@book, @book_comment], local: false do |f| %>
          <%= f.text_area :comment, rows: '5', class: 'w-100', placeholder: "コメント" %>
          <%= f.submit "送信" %>
          <% end %>
          </td>
        </tr>
      </table>

      <div>

    </div>
  </div>
</div>

app/views/favorites/_favorite-btn.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), class: book.favorites.count > 0 ? "text-danger":"text-info", method: :delete, remote: true do %>
    ♥<%= book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), class: book.favorites.count > 0 ? "text-danger":"text-info", method: :post, remote: true do %>
    ♥<%= book.favorites.count %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$("#favorite-btn-<%= @book.id %>").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/favorites/destroy.js.erb
$("#favorite-btn-<%= @book.id %>").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/relationships/_followed.html.erb
<% if relationships.present? %>
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% relationships.each do |relationship| %>
      <tr>
        <td><%= image_tag relationship.follower.get_profile_image, size: '50x50' %></td>
        <td><%= relationship.follower.name %></td>
        <td>フォロー数: <%= relationship.follower.followers.count %></td>
        <td>フォロワー数: <%= relationship.follower.followeds.count %></td>
        <td><%= link_to 'Show', relationship.follower, class: "user_#{relationship.follower.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
ユーザーはいません。
<% end %>

app/views/relationships/_follower.html.erb
<% if relationships.present? %>
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% relationships.each do |relationship| %>
      <tr>
        <td><%= image_tag relationship.followed.get_profile_image, size: '50x50' %></td>
        <td><%= relationship.followed.name %></td>
        <td>フォロー数: <%= relationship.followed.followers.count %></td>
        <td>フォロワー数: <%= relationship.followed.followeds.count %></td>
        <td><%= link_to 'Show', relationship.followed, class: "user_#{relationship.followed.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
ユーザーはいません。
<% end %>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/relationships/followed.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-12 offset-md-1'>
      <h2>Follower Users</h2>
      <%= render 'followed', relationships: @relationships %>
    </div>
  </div>
</div>

app/views/relationships/follower.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-12 offset-md-1'>
      <h2>Follow Users</h2>
      <%= render 'follower', relationships: @relationships %>
    </div>
  </div>
</div>

app/views/searches/_book.html.erb
<% if books.present? %>
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user.id) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td>
        <% if book.favorited_by?(current_user) %>
          <%= link_to book_favorites_path(book), class: book.favorites.count > 0 ? "text-danger":"text-info", method: :delete do %>
            ♥<%= book.favorites.count %>
          <% end %>
        <% else %>
          <%= link_to book_favorites_path(book), class: book.favorites.count > 0 ? "text-danger":"text-info", method: :post do %>
            ♥<%= book.favorites.count %>
          <% end %>
        <% end %>
        </td>
        <td>コメント数:<%= book.book_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/searches/_form.html.erb
<% if user_signed_in? %>
    <%= form_tag(search_path, method: :get) do %>
      <%= text_field_tag('content', value = @content) %>
      <%= select_tag 'model', options_for_select({ "User" => :user, "Book" => :book }, :selected => @model) %>
      <%= select_tag 'type', options_for_select({ "完全一致" => :perfect, "部分一致" => :partial }, :selected => @type) %>
      <%= submit_tag '検索' %>
    <% end %>
<% end %>

app/views/searches/_user.html.erb
<% if users.present? %>
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followers.count %></td>
        <td>フォロワー数: <%= user.followeds.count %></td>
        <td>
        <% if user != current_user %>
          <% if current_user.follow_to?(user) %>
            <%= link_to user_relationships_path(user), method: :delete do %>
            フォロー外す
            <% end %>
          <% else %>
            <%= link_to user_relationships_path(user), method: :post do %>
            フォローする
            <% end %>
          <% end %>
        <% end %>
        </td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/searches/search.html.erb
<h1>
  <%= "#{@model.pluralize.capitalize} search for \"#{@content}\"" %>
</h1>

<% if @model == :book.to_s %>
<%= render 'book', books: @books %>
<% elsif @model == :user.to_s %>
<%= render 'user', users: @users %>
<% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followers.count %></td>
        <td>フォロワー数: <%= user.followeds.count %></td>
        <td>
        <% if user != current_user %>
          <% if current_user.follow_to?(user) %>
            <%= link_to user_relationships_path(user), method: :delete do %>
            フォロー外す
            <% end %>
          <% else %>
            <%= link_to user_relationships_path(user), method: :post do %>
            フォローする
            <% end %>
          <% end %>
        <% end %>
        </td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
	  <th>follows</th>
	  <th>
	    <%= link_to user_follower_path(user) do %>
	    <%= user.followers.count %></th>
	    <% end %>
  </tr>
  <tr>
	  <th>followers</th>
	  <th>
	    <%= link_to user_followed_path(user) do %>
	    <%= user.followeds.count %></th>
	    <% end %>
  </tr>
</table>

<div class='row'>
<% if @user == current_user %>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
<% else %>
  <% if current_user.follow_to?(user) %>
    <%= link_to user_relationships_path(user), class: "btn btn-info btn-block follow_user_#{user.id}", method: :delete do %>
    フォローを外す
    <% end %>
  <% else %>
    <%= link_to user_relationships_path(user), class: "btn btn-success btn-block follow_user_#{user.id}", method: :post do %>
    フォローする
    <% end %>
  <% end %>
<% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>